### ISSUE TITLE
Error while installing :   File "setup.py", line 116, in <module> / AttributeError: 'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by tugdualnicolas** [the-Infected-Drake/TIDoS-Framework#12]
The output of the installation while i run : sudo python setup.py
`Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    pip.main(["install", "scapy", "requests", "google"])
AttributeError: 'module' object has no attribute 'main'
`

**Comment by the-Infected-Drake** [comment]
I guess you are having problem with pip. This is not a problem with my code.

Anyways, I am working on version 2.1.0 of this project and will be updating soon. Please keep patience till then.
:)

> @_tID
